// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG3Nz0t1ENB3SaBchXO3sLZJAVOnQTquY',
    appId: '1:758650797327:web:9268b64fa93422569d527a',
    messagingSenderId: '758650797327',
    projectId: 'currencydetector-f53c3',
    authDomain: 'currencydetector-f53c3.firebaseapp.com',
    databaseURL:
        'https://currencydetector-f53c3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'currencydetector-f53c3.appspot.com',
    measurementId: 'G-T4CE8W49L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHlsCpThPa2-0UjP9x7VDDhMWLRuV3wQw',
    appId: '1:758650797327:android:3d3b45b7dd4edae49d527a',
    messagingSenderId: '758650797327',
    projectId: 'currencydetector-f53c3',
    databaseURL:
        'https://currencydetector-f53c3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'currencydetector-f53c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4LvmrhtJhUlNn1cgZyFW_w_54LekihPA',
    appId: '1:758650797327:ios:abe053efaf64976a9d527a',
    messagingSenderId: '758650797327',
    projectId: 'currencydetector-f53c3',
    databaseURL:
        'https://currencydetector-f53c3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'currencydetector-f53c3.appspot.com',
    iosClientId:
        '758650797327-o0svm0ethsbkaeqh17nbpvajru6a1hvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.currencyDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4LvmrhtJhUlNn1cgZyFW_w_54LekihPA',
    appId: '1:758650797327:ios:abe053efaf64976a9d527a',
    messagingSenderId: '758650797327',
    projectId: 'currencydetector-f53c3',
    databaseURL:
        'https://currencydetector-f53c3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'currencydetector-f53c3.appspot.com',
    iosClientId:
        '758650797327-o0svm0ethsbkaeqh17nbpvajru6a1hvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.currencyDetector',
  );
}
